;__SOURCE__=__http://www.autohotkey.com/board/topic/_____-windows-color-picker-plus/

/*!
____Function:__ChooseColor([pRGB,__hOwner,__DlgX,__DlgY,__Palette])
________Displays__a__standard__Windows__dialog__for__choosing__colors.

____Parameters:
________pRGB__-__The__initial__color__to__display__in__the__dialog__in__RGB__format.
________________The__default__setting__is__Black.
________hOwner__-__The__Window__ID__of__the__dialog's__owner,__if__it__has__one.__Defaults__to
_________________,__i.e.__no__owner.__If__specified__DlgX__and__DlgY__are__ignored.
________DlgX,__DlgY__-__The__X__and__Y__coordinates__of__the__upper__left__corner__of__the__
______________________dialog.__Both__default__to___.
________Palette__-__An__array__of__up__to______RGB__color__values.__These__become__the__
__________________initial__custom__colors__in__the__dialog.

____Remarks:
________The__custom__colors__in__the__dialog__are__remembered__between__calls.
________
________If__the__user__selects__OK,__the__Palette__array__(if__it__exists)__will__be__loaded__
________with__the__custom__colors__from__the__dialog.__

____Returns:
________If__the__user__selects__OK,__the__selected__color__is__returned__in__RGB__format__
________and__ErrorLevel__is__set__to___.__Otherwise,__the__original__pRGB__value__is__
________returned__and__ErrorLevel__is__set__to___.
*/
ChooseColor(pRGB__:=___,__hOwner__:=___,__DlgX__:=___,__DlgY__:=___,__Palette*)
{
____static__CustColors____;__Custom__colors__are__remembered__between__calls
____static__SizeOfCustColors__:=__VarSetCapacity(CustColors,____,___)
____static__StructSize__:=__VarSetCapacity(ChooseColor,_____*__A_PtrSize,___)
____
____CustData__:=__(DlgX__<<____)__|__DlgY____;__Store__X__in__high__word,__Y__in__the__low__word

;___Load__user's__custom__colors
____for__Index,__Value__in__Palette
________NumPut(BGR_RGB(Value),__CustColors,__(Index__-___)__*___,__"UInt")

;___Set__up__a__ChooseColor__structure__as__described__in__the__MSDN
____NumPut(StructSize,__ChooseColor,___,__"UInt")
____NumPut(hOwner,__ChooseColor,__A_PtrSize,__"UPtr")
____NumPut(BGR_RGB(pRGB),__ChooseColor,_____*__A_PtrSize,__"UInt")
____NumPut(&CustColors,__ChooseColor,_____*__A_PtrSize,__"UPtr")
____NumPut(_x___,__ChooseColor,_____*__A_PtrSize,__"UInt")
____NumPut(CustData,__ChooseColor,_____*__A_PtrSize,__"UInt")
____NumPut(RegisterCallback("ColorWindowProc"),__ChooseColor,_____*__A_PtrSize,__"UPtr")

;___Call__the__function
____ErrorLevel__:=__!__DllCall("comdlg__\ChooseColor",__"UPtr",__&ChooseColor,__"UInt")

;___Save__the__changes__made__to__the__custom__colors
____if__not__ErrorLevel
________Loop____
____________Palette[A_Index]__:=__BGR_RGB(NumGet(CustColors,__(A_Index__-___)__*___,__"UInt"))
________
____return__BGR_RGB(NumGet(ChooseColor,_____*__A_PtrSize,__"UINT"))
}

/*!
____Function:__ColorWindowProc(hwnd,__msg,__wParam,__lParam)
________Callback__function__used__to__modify__the__Color__dialog__before__it__is__displayed

____Parameters:
________hwnd__-__Handle__to__the__Color__dialog__window.
________msg__-__The__message__sent__to__the__window.
________wParam__-__The__handle__to__the__control__that__has__the__keyboard__focus.
________lParam__-__A__pointer__to__the__ChooseColor__structure__associated__with__the__
__________________Color__dialog.

____Remarks:
________This__is__intended__to__be__a__private__function,__called__only__by__ChooseColor.__
________In__response__to__a__WM_INITDIALOG__message,__this__function__can__be__used__to__
________modify__the__Color__dialog__before__it__is__displayed.__Currently__it__just__moves__
________the__window__to__a__new__X,__Y__location.

____Returns:
________If__the__hook__procedure__returns__zero,__the__default__dialog__box__procedure__
________also__processes__the__message.__Otherwise,__the__default__dialog__box__procedure__
________ignores__the__message.
*/
ColorWindowProc(hwnd,__msg,__wParam,__lParam)
{
____static__WM_INITDIALOG__:=___x____
____
____if__(msg__<>__WM_INITDIALOG)
________return___
____
____hOwner__:=__NumGet(lParam+_,__A_PtrSize,__"UPtr")
____if__(hOwner)
________return___

____DetectSetting__:=__A_DetectHiddenWindows
____DetectHiddenWindows__On
____CustData__:=__NumGet(lParam+_,_____*__A_PtrSize,__"UInt")
____DlgX__:=__CustData__>>____,__DlgY__:=__CustData__&___xFFFF
____WinMove__ahk_id__%hwnd%,__,__%DlgX%,__%DlgY%
____
____DetectHiddenWindows__%DetectSetting%
____return___
}

/*!
____Function:__BGR_RGB(Color)
________Converts__a__BGR__color__value__to__a__RGB__one__or__vice__versa.

____Parameters:
________Color__-__The__BGR__or__RGB__value__to__convert

____Returns:
________The__converted__value.
*/
BGR_RGB(Color)
{
____return__(Color__&___xFF______)__
__________|__((Color__&___xFF____)__>>____)__
__________|__(Color__&___x__FF__)__
__________|__((Color__&___x____FF)__<<____)
}